### ISSUE TITLE
Code live anywhere

### ISSUE THREAD

**Issue by shivan-s** [MaorMohav/Infopacity#1]
Hi there, I'm wondering if this project is live anywhere?

**Comment by MaorMohav** [comment]
Hi,
The project was uploaded to the web a year ago as part of the course during my degree and was decided by me  downloading it from the web due to lack of use.
I attached a video and summary file about the project in Hebrew that explains the project.

The video is available in my drive :
https://drive.google.com/drive/folders/1c-NPJcoJf44L8NWMJ0zouWzymikg4XXU
